
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 26 23:46:48 ART 2021
//----------------------------------------------------

package ar.edu.ub.dc.compilador_aritmetico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int POR = 7;
  public static final int INICIO = 2;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int MAS = 5;
  public static final int NUMERO = 15;
  public static final int ASIGNACION = 10;
  public static final int MODULO = 9;
  public static final int error = 1;
  public static final int RPAREN = 14;
  public static final int DIVISION = 8;
  public static final int IDENTIFIER = 11;
  public static final int PUNTOYCOMA = 4;
  public static final int IMPRIMIR = 12;
  public static final int LPAREN = 13;
}

