
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 10 22:02:47 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_aritmetico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int POR = 5;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int NUMERO = 10;
  public static final int MODULO = 7;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int DIVISION = 6;
  public static final int PUNTOYCOMA = 2;
  public static final int LPAREN = 8;
}

