
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 31 21:23:25 ART 2021
//----------------------------------------------------

package simplelanguage;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int PUNTOYCOMA = 4;
  public static final int ELSE = 15;
  public static final int RPAREN = 20;
  public static final int L_LLAVE = 21;
  public static final int THEN = 14;
  public static final int DIVISION = 8;
  public static final int R_LLAVE = 22;
  public static final int IDENTIFIER = 11;
  public static final int IMPRIMIR = 12;
  public static final int MODULO = 9;
  public static final int IF = 13;
  public static final int LPAREN = 19;
  public static final int POR = 7;
  public static final int IGUALDAD = 17;
  public static final int ASIGNACION = 10;
  public static final int EOF = 0;
  public static final int NUMERO = 23;
  public static final int error = 1;
  public static final int FOR = 16;
  public static final int FIN = 3;
  public static final int MAS = 5;
  public static final int DESIGUALDAD = 18;
  public static final int INICIO = 2;
}

