
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 04 02:26:28 ART 2021
//----------------------------------------------------

package simplelanguage;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int ELSE = 17;
  public static final int PUNTOYCOMA = 4;
  public static final int RPAREN = 22;
  public static final int L_LLAVE = 23;
  public static final int THEN = 16;
  public static final int LOOP = 18;
  public static final int DIVISION = 8;
  public static final int R_LLAVE = 24;
  public static final int IDENTIFIER = 13;
  public static final int IMPRIMIR = 14;
  public static final int MODULO = 9;
  public static final int IF = 15;
  public static final int LPAREN = 21;
  public static final int POR = 7;
  public static final int IGUALDAD = 19;
  public static final int PlUSONEACCUMULATOR = 11;
  public static final int ASIGNACION = 12;
  public static final int EOF = 0;
  public static final int NUMERO = 25;
  public static final int error = 1;
  public static final int FIN = 3;
  public static final int MAS = 5;
  public static final int ACCUMULATOR = 10;
  public static final int DESIGUALDAD = 20;
  public static final int INICIO = 2;
}

